module.exports = {
  title: ``,
  description: ``,
  author: `quyennt`,
  language: 'vi-VN',
  siteUrl: 'https://quyennt.gtsb.io',
  comment: `Hi, I'm Sr. Software Engineer, I write a blog about lifestyle and personal growth.`,
  name: 'Quyen Nguyen',
  company: '',
  location: 'Ha noi',
  email: 'ken.tb997@gmail.com',
  website: '',
  facebook: 'https://www.facebook.com/quyennt21',                                    
  instagram: 'https://www.instagram.com/quyennt_',
  github: 'https://github.com/quyennt21',
};
