module.exports = {
  title: `Quyen's Blog`,
  description: ``,
  author: `Quyen`,
  language: 'vi-VN',
  siteUrl: 'https://quyennt.gtsb.io',
  comment: 'Freelancer',
  name: 'Quyen',
  company: '',
  location: 'Vietnam',
  email: 'ken.tb997@gmail.com',
  website: 'https://quyennt.gtsb.io',
  facebook: 'https://www.facebook.com/quyennt21',                                    
  instagram: 'https://www.instagram.com/quyennt_',
  github: 'https://github.com/quyennt21',
};
